import pyautogui
import time
import os

class Recorder:

    def __init__(self):
        self.x, self.y = pyautogui.size()
        self.x = self.x / 2
        self.y = self.y / 2 + 50
        self.record1()
        time.sleep(5)
        self.record2()
        time.sleep(5)
        self.record3()

    def record1(self):
        time.sleep(5)
        pyautogui.keyDown('command')
        pyautogui.press('4')
        pyautogui.keyUp('command')
        os.system('xcrun simctl openurl booted http://localhost:1337/localhost/Statements.html')
        pyautogui.keyDown('command')
        pyautogui.press('r')
        pyautogui.keyUp('command')
        time.sleep(3)
        pyautogui.click(self.x, self.y)
        pyautogui.keyDown('down')
        time.sleep(2)
        pyautogui.keyUp('down')
        pyautogui.moveTo(870, 720)
        pyautogui.click()
        time.sleep(3)
        pyautogui.moveTo(870, 170)
        pyautogui.click()
        time.sleep(1.5)
        pyautogui.moveTo(580, 720)
        time.sleep(1)
        pyautogui.click()
        pyautogui.moveTo(self.x, self.y)
        pyautogui.click()
        pyautogui.keyDown('down')
        time.sleep(2)
        pyautogui.keyUp('down')
        pyautogui.moveTo(850, 60)
        pyautogui.click()

    def record2(self):
        time.sleep(5)
        pyautogui.keyDown('command')
        pyautogui.press('4')
        pyautogui.keyUp('command')
        os.system('xcrun simctl openurl booted http://localhost:1337/localhost/Statements.html')
        time.sleep(3)
        pyautogui.keyDown('command')
        pyautogui.press('r')
        pyautogui.keyUp('command')
        pyautogui.click(self.x, self.y)
        pyautogui.keyDown('down')
        time.sleep(2)
        pyautogui.keyUp('down')
        pyautogui.moveTo(870, 720)
        pyautogui.click()
        time.sleep(3)
        pyautogui.moveTo(870, 170)
        pyautogui.click()
        time.sleep(1.5)
        pyautogui.moveTo(780, 720)
        pyautogui.click()
        pyautogui.moveTo(870, 170)
        time.sleep(1)
        pyautogui.click()
        time.sleep(2)
        pyautogui.moveTo(870, 720)
        pyautogui.click()
        time.sleep(1)
        pyautogui.moveTo(870, 170)
        pyautogui.click()
        pyautogui.moveTo(850, 60)
        pyautogui.click()

    def record3(self):
        time.sleep(5)
        pyautogui.keyDown('command')
        pyautogui.press('4')
        pyautogui.keyUp('command')
        os.system('xcrun simctl openurl booted http://localhost:1337/localhost/Profile.html')
        time.sleep(1)
        pyautogui.keyDown('command')
        pyautogui.press('r')
        pyautogui.keyUp('command')
        time.sleep(2)
        pyautogui.keyDown('down')
        time.sleep(0.5)
        pyautogui.keyUp('down')
        pyautogui.moveTo(870, 720)
        pyautogui.click()
        time.sleep(3)
        pyautogui.moveTo(870, 680)
        pyautogui.click()
        time.sleep(2)
        pyautogui.click(self.x, self.y)
        pyautogui.keyDown('down')
        time.sleep(2)
        pyautogui.keyUp('down')
        pyautogui.moveTo(850, 60)
        pyautogui.click()