# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, profile_id: str):
        self.to_close = False
        self.profile_id = profile_id
        with open('./data/profiles_main.txt', encoding='utf8') as f:
            info = f.readlines()
            profile_info = ''.join(line for line in info if self.profile_id in line)
            if not profile_info:
                with open('./data/profiles_main.txt', 'a', encoding='utf8') as k:
                    k.write(f'{self.profile_id} {0} {0} {0} {0} {0}\n')
            if profile_info:
                balance = profile_info.split(' ')[1]
                fans = profile_info.split(' ')[2]
                percent = profile_info.split(' ')[3]
                pend = profile_info.split(' ')[4]
                follows = profile_info.split(' ')[5]
            else:
                balance = '0'
                fans = '0'
                percent = '0'
                pend = '0'
                follows = '0'
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(350, 430)
        MainWindow.setStyleSheet("QMainWindow {\n"
                                 "background: white;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton {\n"
                                 "background-color: rgb(160, 160, 160);\n"
                                 "border-radius: 17%;\n"
                                 "color: white;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "background-color: rgb(96, 96, 96);\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet("color: black;")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 65, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("color: black;")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 80, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText(balance)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 182, 58, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet("color: black;")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 180, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setText(fans)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 232, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("color: black;")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 230, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setText(percent)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setFont(font)
        self.label_5.setGeometry(QtCore.QRect(30, 132, 131, 16))
        self.label_5.setStyleSheet("color: black;")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 130, 113, 21))
        self.lineEdit_4.setText(pend)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setFont(font)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 131, 16))
        self.label_6.setStyleSheet("color: black;")
        self.label_6.setText("Подписок")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(190, 280, 113, 21))
        self.lineEdit_5.setText(follows)
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(40, 350, 261, 41))
        self.button.setFont(font)
        self.button.clicked.connect(self.save)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Основые настройки"))
        self.label.setText(_translate("MainWindow", "Профиль"))
        self.label_2.setText(_translate("MainWindow", "Баланс:"))
        self.label_5.setText(_translate("MainWindow", "Втор. баланс:"))
        self.label_3.setText(_translate("MainWindow", "Фанс:"))
        self.label_4.setText(_translate("MainWindow", "Топ (процент):"))
        self.button.setText(_translate("MainWindow", "Сохранить"))

    def save(self):
        with open('./data/profiles_main.txt', encoding='utf8') as f:
            info = f.readlines()
        info = [line.strip() for line in info]
        for line in info:
            profile_info = line.split(' ')
            if profile_info[0] == self.profile_id:
                info.remove(line)
                profile_info = [self.profile_id, self.lineEdit.text(), self.lineEdit_2.text(), self.lineEdit_3.text(), self.lineEdit_4.text(), self.lineEdit_5.text()]
                info.append(' '.join(profile_info))
                break
        with open('./data/profiles_main.txt', 'w', encoding='utf8') as f:
            f.writelines(line + '\n' for line in info)
        self.to_close = True